### ISSUE TITLE
Coding Style

### ISSUE THREAD

**Issue by severinkaderli** [sindreslungaard/duel-masters#1]
Hey, thanks for releasing the code for this! I only briefly looked over the code but so far it looks very modular and easy to use, great job!

One thing I noticed is the kinda inconsistent coding style. E.g. some classes are lower case, while other are upper case. It might be a good idea to use a linter like [eslint](https://github.com/typescript-eslint/typescript-eslint) or [tslint](https://github.com/palantir/tslint) to enforce a consistent style. You then could even use something like [husky](https://github.com/typicode/husky) to enforce the code style for commits.

This is just a small thing but I think it can be important when multiple people will contribute to this project.

**Comment by sindreslungaard** [comment]
Hi, thanks :)

There's no classes in the repo, but I assume you're referring to the interfaces in src/game/cards/types which are indeed lowercase as opposed to all other interfaces in the repo. Will be updated.

As for adding a linter, that's a good idea. There's a big job ahead for testing & ci in general, especially for the card implementations where the idea is that you are not allowed to modify the state of the game directly other than through the available effects.
